### ISSUE TITLE
this.renderer is undefined

### ISSUE THREAD

**Issue by unionthugface** [PolymerLabs/iron-overlay#10]
On `_openChanged`, browser throws error `this.renderer is undefined`.  Code works fine in Chrome but not in Firefox.  

See preview here: https://bassface.dance/event-card-list/event-card-list

Browsers affected:
- [ ] Chrome
- [X] Firefox

**Comment by valdrinkoshi** [comment]
looks like you're setting `opened = false` in the `<event-drawer>`. `<iron-overlay>` currently expects doesn't handle that case (aka it expects that the first setting of `opened` is gonna be `opened = true`. The reasoning was that you can save yourself a observer callback invocation.
A quick fix would be to avoid setting that default value to be `false`.
Will fix it in here anyways 👌
