### ISSUE TITLE
Position the iron-overlay nearby another element

### ISSUE THREAD

**Issue by ThomasStrohm** [PolymerLabs/iron-overlay#11]
Hi
I'm playing around with the iron-overlay and I want to position this element nearby another element. 
But the overlay is always in the middle of the site.
I've tried something like this, but it doesn't work.
```
[data-overlay="overlay"] {
    left: var(--left);
    bottom:  var(--bottom);
    top: auto;
    right: auto;
}
``` 

```
connectedCallback() {
    super.connectedCallback();

    this.updateStyles({'--left': '30px'});
    this.updateStyles({'--bottom': '30px'});
}
```

```
<iron-overlay id="overlay" animated>
    <template>
        My overlay	
    </template>
</iron-overlay>
```

Thanks for any help!

**Comment by valdrinkoshi** [comment]
You need to apply those styles in the scope where the renderer is hosted (by default in `<body>`).
You could also set those from through the overlay, e.g.
```js
overlay.opened = true;
overlay.renderer.style.left = '30px';
overlay.renderer.style.bottom = '30px';
```

**Comment by ThomasStrohm** [comment]
Thanks! That's workin
